libs =
import libs += lyrahgames-pareto%lib{lyrahgames-pareto}
import libs += lyrahgames-gnuplot%lib{lyrahgames-gnuplot}

exe{pareto-line-cutter}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
